### ISSUE TITLE
Problem with http3 when trying to make a call()

### ISSUE THREAD

**Issue by p0st1t** [p2p-org/solanaj#17]
Hello, 

I'm sorry if this error is stupid, but i can't make a simple call with the  solanaj client.

I'm working with spring boot. I compiled successfully solanaj and integrated it in my maven pom, build is ok.

I'm just trying to call the "getProgramAccounts" endpoint like this : 
 
```
 RpcClient client = new RpcClient(Cluster.MAINNET);
 String result = client.call("getProgramAccounts", List.of("PUBLIC_KEY"), String.class);
 LOGGER.info(result);
```

Error returned : 

> java.lang.NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(java.lang.String, okhttp3.MediaType)'
	at org.p2p.solanaj.rpc.RpcClient.call(RpcClient.java:56) ~[solanaj-1.6-SNAPSHOT.jar:na]
	
It looks like the okhttp3 method used by solanaj don't exist. I tried to put manually the okhttp3 dependency in the pom like mentionned here, but same error again : https://github.com/web3j/web3j/issues/1271#issuecomment-732106618

Again, i'm sorry if i missed something. I haven't found any documentation on this .call() method..

If anybody can help me it will be really appreciable.

Anyway, thank you for your work with solanaj.

JDK version : 11
Springboot version : 2.5.7
Solanaj version : 1.6-SNAPSHOT

**Comment by p0st1t** [comment]
Ok so yes i was stupid, i just see the client.getApi().getProgramAccounts method..

But i have another error and i really don't understand, there is the error : 

> java.lang.NoSuchFieldError: Companion
> 	at okhttp3.internal.Util.<clinit>(Util.kt:71) ~[okhttp-4.9.0.jar:na]
> 	at okhttp3.internal.concurrent.TaskRunner.<clinit>(TaskRunner.kt:309) ~[okhttp-4.9.0.jar:na]
> 	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:41) ~[okhttp-4.9.0.jar:na]
> 	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:47) ~[okhttp-4.9.0.jar:na]
> 	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:471) ~[okhttp-4.9.0.jar:na]
> 	at org.p2p.solanaj.rpc.RpcClient.<init>(RpcClient.java:41) ~[solanaj-1.6-SNAPSHOT.jar:na]
> 	at org.p2p.solanaj.rpc.RpcClient.<init>(RpcClient.java:36) ~[solanaj-1.6-SNAPSHOT.jar:na]
> 

And the source code used for that : 

```
RpcClient client = new RpcClient(Cluster.MAINNET);
        ProgramAccountConfig conf = new ProgramAccountConfig(RpcSendTransactionConfig.Encoding.base64);
        List<ProgramAccount> result = client.getApi().getProgramAccounts(new PublicKey("PUB_KEY"), conf);
        for(ProgramAccount p : result){
            LOGGER.info(p.getPubkey());
        }
```

I don't understand what is this field "Companion", can someone help me a little please ?..

**Comment by p0st1t** [comment]
Ok, so strange.

Theses error happens when i start the project directly with the spring boot starter on intellij.

When i start the war builded with "java -jar my-war.war", no problem, it works well.

So, sorry for this useless issue.
